#!/bin/sh
set -e
PKG_TOPDIR=$(cd $(dirname $0)/../../ && pwd -P)
base_url=https://github.com/measurement-kit/prebuilt/releases/download
while [ $# -gt 0 ]; do
  package=$1 # E.g.: testing/iphonesimulator-x86_64-libressl-2.6.4-1
  shift
  basename=`basename $package`
  os=`echo $basename | cut -d- -f1`
  arch=`echo $basename | cut -d- -f2`
  remainder=`echo $basename | cut -d- -f3-`
  set -x
  curl -Lso $basename.tar.gz $base_url/$package.tar.gz
  checksum=`cat ${PKG_TOPDIR}/checksum/$os/$arch/$remainder.txt`
  test "$checksum" = "`cmake -E sha256sum $basename.tar.gz | awk '{print $1}'`"
  tar -xzf $basename.tar.gz
  rm -rf $basename.tar.gz
  set +x
done
