#!/bin/sh
set -e
base_url=https://github.com/measurement-kit/prebuilt/releases/download
while [ $# -gt 0 ]; do
  package=$1 # E.g.: testing/iphonesimulator-x86_64-libressl-2.6.4-1
  shift
  basename=`basename $package`
  os=`echo $basename | cut -d- -f1`
  arch=`echo $basename | cut -d- -f2`
  name=`echo $basename | cut -d- -f3`
  version=`echo $basename | cut -d- -f4`
  build_version=`echo $basename | cut -d- -f5`
  set -x
  curl -Lso $basename.tar.gz $base_url/$package.tar.gz
  checksum=`cat ./checksum/$os/$arch/$name-$version-$build_version.txt`
  test "$checksum" = "`cmake -E sha256sum $basename.tar.gz | awk '{print $1}'`"
  tar -xzf $basename.tar.gz
  set +x
done
